Add new invoicing page
SciLifeLab/genomics-status pull request #701
Opened 2023-01-27 16:17 UTC by aanil

WIP

2023-02-09 15:07 UTC, aanil commented on conda_requirements.yml
> +#name: genstat
```suggestion
name: genstat
```

2023-02-09 16:12 UTC, alneberg requested changes
This will be amazing! I haven't gotten to read through the python file yet, will do tomorrow. Some suggested changes to the UI, but most of it looks very nice!

2023-02-09 20:30 UTC, aanil commented on run_dir/design/invoicing.html
> +                  <th class="sort">View Invoice</th>
Done!

2023-02-09 20:30 UTC, aanil commented on run_dir/design/invoicing.html
> +                    <th class="sort">Date of Generation</th>
Done!

2023-02-09 20:31 UTC, aanil commented on run_dir/static/js/invoicing.js
> +  function init_listjs(table_name) {
Done( for existing tables too)

2023-02-09 20:33 UTC, aanil commented on run_dir/static/js/invoicing.js
> +    $('#gen_invoice_form').attr('action', '/generate_invoice').attr('method', 'post').delay(3000).queue(function(){load_invoicing_table()})
The request submits to a new page, and we can't actually have a promise resolve between pages, I think. So I just refresh the table after 3 seconds.

2023-02-09 20:33 UTC, aanil commented on run_dir/static/js/pricing_quote.js
> +        generate_invoice_spec(){
Done!

2023-02-14 13:51 UTC, alneberg commented
I think we need to figure out a way for the "Mark signed"/"spec generated" to not be untraceably changed after the invoice has been downloaded. I guess we're not supposed to do that but I find it a bit troublesome that if it's done, one won't even know.

2023-02-14 14:30 UTC, aanil commented
> I think we need to figure out a way for the "Mark signed"/"spec generated" to not be untraceably changed after the invoice has been downloaded. I guess we're not supposed to do that but I find it a bit troublesome that if it's done, one won't even know.

Change the field to a list?

2023-02-15 17:06 UTC, alneberg approved these changes
Woohoo! Let's go!

2023-02-15 17:06 UTC, merged